### ISSUE TITLE
Confusing error message on syntax error

### ISSUE THREAD

**Issue by BernieSumption** [LearnBoost/stylus#1817]
Not exactly a critical bug, but this had be scratching my head for a few minutes.

I had a file with a syntax error, the exclamation mark on line 2:

```
.container
  margin 50px auto!

.foo
  color: red
```

Compiling this file causes an internal error "Cannot call method 'clone' of undefined" with a source view that highlights the last statement in the file rather than the actual statement responsible.

```
stylus stylus-bug-demo.styl 

/usr/local/lib/node_modules/stylus/bin/stylus:646
              throw err;
                    ^
TypeError: stylus-bug-demo.styl:5:13
   1| .container
   2|   margin 50px auto!
   3| 
   4| .foo
   5|   color: red
------------------^

Cannot call method 'clone' of undefined

    at UnaryOp.clone (/usr/local/lib/node_modules/stylus/lib/nodes/unaryop.js:43:26)
    at /usr/local/lib/node_modules/stylus/lib/nodes/expression.js:86:17
    at Array.map (native)
    at Expression.clone (/usr/local/lib/node_modules/stylus/lib/nodes/expression.js:85:28)
    at Property.clone (/usr/local/lib/node_modules/stylus/lib/nodes/property.js:49:41)
    at /usr/local/lib/node_modules/stylus/lib/nodes/block.js:93:21
    at Array.forEach (native)
    at Block.clone (/usr/local/lib/node_modules/stylus/lib/nodes/block.js:92:14)
    at Group.clone (/usr/local/lib/node_modules/stylus/lib/nodes/group.js:90:28)
    at /usr/local/lib/node_modules/stylus/lib/nodes/root.js:65:21
```

**Comment by Panya** [comment]
Thanks for the report. I've fixed this bug in the `dev` branch. The fix will be in the next release.
