### ISSUE TITLE
Keeping six-digit colors intact

### ISSUE THREAD

**Issue by ruandre** [LearnBoost/stylus#1825]
Stylus converts six-digit colors down to three where possible.
For example: `#00ff00` to `#0f0`

Is there an option I can pass to Stylus to disable this?
I'm trying to keep six-digit colors for HTML emails.

**Comment by Panya** [comment]
There is no option for this currently, but you can write a JS-plugin. For example:
`raw-color.js`
```js
module.exports = function() {
  return function(styl) {
    var nodes = styl.nodes;
    nodes.RGBA.prototype.toString = function() {
      return this.raw;
    };

    nodes.HSLA.prototype.toString = nodes.RGBA.prototype.toString;
  };
};
```

```sass
use('raw-color.js')

.body
  test: #cc0000
```

Compiles to:
```css
.body {
  test: #cc0000;
}
```

**Comment by ruandre** [comment]
I get the following error:

```bash
/path/node_modules/gulp-stylus/node_modules/stylus/lib/renderer.js:202
  fn.call(this, this);
     ^
TypeError: Object raw-color.js has no method 'call'
    at Renderer.use (/path/node_modules/gulp-stylus/node_modules/stylus/lib/renderer.js:202:6)
    at Stylus._render (/path/node_modules/gulp-stylus/node_modules/accord/lib/adapters/stylus.js:95:14)
    at Stylus.Adapter.render (/path/node_modules/gulp-stylus/node_modules/accord/lib/adapter_base.js:122:19)
    at DestroyableTransform._transform (/path/node_modules/gulp-stylus/index.js:32:12)
    at DestroyableTransform.Transform._read (/path/node_modules/gulp-stylus/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/path/node_modules/gulp-stylus/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/path/node_modules/gulp-stylus/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/path/node_modules/gulp-stylus/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/path/node_modules/gulp-stylus/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/path/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
```

**gulpfile.js**
```js
...

stylus = require( 'gulp-stylus' );

gulp.task( 'stylus', function() {
  return gulp.src( 'src/styl/*.styl' )
    .pipe( stylus( { compress: false, use: 'raw-color.js' } ) )
    .pipe( gulp.dest( 'temp' ) );
} );

...
```
**email.styl**
```css
use('raw-color.js')

body
  color #000000
```

**Folder:**
```
gulpfile.js
node_modules
package.json
raw-color.js
```

Am I using the `raw-color.js` file correctly?

**Comment by Panya** [comment]
No, no need to add it to `use` in the grunt file.

**Comment by ruandre** [comment]
Yup, my path wasn't correct. Thanks so much Panya!
