### ISSUE TITLE
Call function with string notation

### ISSUE THREAD

**Issue by hikkyu** [LearnBoost/stylus#1867]
Hello!

I try to do something like that:

```stylus
aSuperFunctionName() {
    return 23px
}

body {
    left: ['aSuperFunctionName']();
}
```

But I got this exception:

```node
/Users/berseron/npm/lib/node_modules/stylus/bin/stylus:661
              throw err;
                    ^
TypeError: ./examples/stylus/function.styl:8:1
   4| 
   5| body {
   6|   left: ['aSuperFunctionName']();
   7| }
   8| 
------^

Cannot call method 'clone' of undefined

    at BinOp.clone (/Users/berseron/npm/lib/node_modules/stylus/lib/nodes/binop.js:45:26)
    at /Users/berseron/npm/lib/node_modules/stylus/lib/nodes/expression.js:86:17
    at Array.map (native)
    at Expression.clone (/Users/berseron/npm/lib/node_modules/stylus/lib/nodes/expression.js:85:28)
    at Property.clone (/Users/berseron/npm/lib/node_modules/stylus/lib/nodes/property.js:49:41)
    at /Users/berseron/npm/lib/node_modules/stylus/lib/nodes/block.js:93:21
    at Array.forEach (native)
    at Block.clone (/Users/berseron/npm/lib/node_modules/stylus/lib/nodes/block.js:92:14)
    at Group.clone (/Users/berseron/npm/lib/node_modules/stylus/lib/nodes/group.js:90:28)
    at /Users/berseron/npm/lib/node_modules/stylus/lib/nodes/root.js:65:21
```

Is there a way to do something like that ?

Thank's

**Comment by Panya** [comment]
Well, if you already know a function name (`aSuperFunctionName` in your case) then you can just call it by the name:
```styl
aSuperFunctionName() {
    return 23px
}

body {
    left: aSuperFunctionName();
}
```

And if you're trying to call function with dynamic generated name (e.g. name of the function stored in some variable), you can use `lookup` bif and write:
```styl
aSuperFunctionName() {
    return 23px
}

dynamicName = 'aSuperFunctionName'

body {
    fn = lookup(dynamicName);
    left: fn();
}
```

**Comment by hikkyu** [comment]
Thank's a lot!
