### ISSUE TITLE
CL --watch on Windows dies when it encounters an error

### ISSUE THREAD

**Issue by walling** [LearnBoost/stylus#591]
The `--watch` argument works fine on Windows as long as there are no errors in the Stylus files, but it dies on the first error encountered.

I tried with and without running Growl for Windows. There is no difference in behavior. Command line output:

```

Error: screen.styl:1
 > 1| @import "lib/test"
   2|
   3| html
   4|   background-color #fff

failed to locate @import file lib/test.styl

    at Evaluator.visitImport (c:\Users\digroli\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:647:21)
    at Evaluator.<anonymous> (c:\Users\digroli\AppData\Roaming\npm\node_modules\stylus\lib\visitor\index.js:28:39)
    at Evaluator.visit (c:\Users\digroli\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:75:18)
    at Evaluator.visitRoot (c:\Users\digroli\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:510:27)
    at Evaluator.<anonymous> (c:\Users\digroli\AppData\Roaming\npm\node_modules\stylus\lib\visitor\index.js:28:39)
    at Evaluator.visit (c:\Users\digroli\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:75:18)
    at Evaluator.evaluate (c:\Users\digroli\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:145:15)
    at Renderer.render (c:\Users\digroli\AppData\Roaming\npm\node_modules\stylus\lib\renderer.js:69:26)
    at c:\Users\digroli\AppData\Roaming\npm\node_modules\stylus\bin\stylus:504:15
    at [object Object].<anonymous> (fs.js:115:5)

c:\Users\digroli\AppData\Roaming\npm\node_modules\stylus\bin\stylus:509
              growl && growl.notify(err.message, { title: 'Stylus error' });
                             ^
TypeError: Object function growl(msg, options, fn) {
  var image
    , args = [cmd.pkg]
    , options = options || {}
    , fn = fn || function(){};

  // noop
  if (!cmd) return fn(new Error('growl not supported on this platform'));

  // image
  if (image = options.image) {
    switch(cmd.type) {
      case 'Darwin':
        var flag, ext = path.extname(image).substr(1)
        flag = flag || ext == 'icns' && 'iconpath'
        flag = flag || /^[A-Z]/.test(image) && 'appIcon'
        flag = flag || /^png|gif|jpe?g$/.test(ext) && 'image'
        flag = flag || ext && (image = ext) && 'icon'
        flag = flag || 'icon'
        args.push('--' + flag, image)
        break;
      case 'Linux':
        args.push('-i ' + image);
        break;
    }
  }

  // sticky
  if (options.sticky) args.push(cmd.sticky);

  // priority
  if (options.priority) {
    var priority = options.priority + '';
    var checkindexOf = cmd.priority.range.indexOf(priority);
    if (~cmd.priority.range.indexOf(priority)) {
      args.push(cmd.priority, options.priority);
    }
  }

  // name
  if (options.name && cmd.type === "Darwin") {
    args.push('--name', options.name);
  }

  switch(cmd.type) {
    case 'Darwin':
      args.push(cmd.msg);
      args.push('"' + msg + '"');
      if (options.title) args.push(options.title);
      break;
    case 'Linux':
      if (options.title) {
        args.push("'" + options.title + "'");
        args.push(cmd.msg);
        args.push("'" + msg + "'");
      } else {
        args.push("'" + msg + "'");
      }
      break;
  }

  // execute
  exec(args.join(' '), fn);
} has no method 'notify'
    at c:\Users\digroli\AppData\Roaming\npm\node_modules\stylus\bin\stylus:509:30
    at Renderer.render (c:\Users\digroli\AppData\Roaming\npm\node_modules\stylus\lib\renderer.js:86:5)
    at c:\Users\digroli\AppData\Roaming\npm\node_modules\stylus\bin\stylus:504:15
    at [object Object].<anonymous> (fs.js:115:5)
    at [object Object].emit (events.js:64:17)
    at afterRead (fs.js:1111:12)
    at Object.wrapper [as oncomplete] (fs.js:254:17)
```

I'm using Stylus 0.24.0 on Node 0.6.8 on Windows 7 32-bit.

**Comment by Panya** [comment]
Fixed several versions ago.
